config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :staffs
  resources :job_orders
  root to: 'job_orders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      get 'jo' => 'job_orders#index'
      get 'jo/:id' => 'job_orders#show'
      post 'jo' => 'job_orders#create'
      put 'jo/:id' => 'job_orders#update'
      delete 'jo/:id' => 'job_orders#destroy'
    end
  end
end

app/models/staff.rb
class Staff < ApplicationRecord
  has_many :job_orders
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render :show, status: :created, location: @staff }
      else
        format.html { render :new }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { render :show, status: :ok, location: @staff }
      else
        format.html { render :edit }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: 'Staff was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:name, :address, :active, :imei)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
  <% if staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.text_field :active %>
  </div>

  <div class="field">
    <%= form.label :imei %>
    <%= form.number_field :imei %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/staffs/edit.html.erb
<h1>Editing Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staffs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Active</th>
      <th>Imei</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
        <td><%= staff.name %></td>
        <td><%= staff.address %></td>
        <td><%= staff.active %></td>
        <td><%= staff.imei %></td>
        <td><%= link_to 'Show', staff %></td>
        <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
        <td><%= link_to 'Destroy', staff, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New Staff</h1>

<%= render 'form', staff: @staff %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @staff.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @staff.address %>
</p>

<p>
  <strong>Active:</strong>
  <%= @staff.active %>
</p>

<p>
  <strong>Imei:</strong>
  <%= @staff.imei %>
</p>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>

<h4>Recent Orders</h4>

<table>
  <thead>
  <tr>
    <th> Job Number </th>
    <th> Customer Name </th>
  </tr>
  </thead>

  <tbody>
  <% @staff.job_orders.each do |joborder|%>
    <tr>
      <td> <%= joborder.jobnumber %> </td>
      <td> <%= joborder.customer.name %> </td>
    </tr>
  <% end %>
  </tbody>
</table>