config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :staffs
  resources :job_orders
  root to: 'job_orders#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
    namespace :v1 do
      get 'jo' => 'job_orders#index'
      get 'jo/:id' => 'job_orders#show'
      post 'jo' => 'job_orders#create'
      put 'jo/:id' => 'job_orders#update'
      delete 'jo/:id' => 'job_orders#destroy'
    end
  end
end

app/models/job_order.rb
class JobOrder < ApplicationRecord
  belongs_to :staff
  belongs_to :customer

  enum status: { pending:0, on_progress:1, completed:2}
end

app/controllers/api/v1/job_orders_controller.rb
class Api::V1::JobOrdersController < ApplicationController

    def index
      @job_order = JobOrder.all
      render json: {
          values: @job_order,
          message: "Sukses"
      }, status: 200
    end

    def show
      @job_order =JobOrder.find_by_id(params[:id])
        if @job_order.present?
          render json:{
            values: @job_order,
            message: "Sukses",
          }, status: 200
        else
          render json:{
            values: "",
            message: "Data Tidak Ditemukan",
          }, status: 400
        end
    end


    def create
      @job_order = JobOrder.new(job_order_params)

      if @job_order.save
        render json:{
          values: "",
          message: "Sukses",
        }, status: 200
      else
        render json:{
          values: "",
          message: "Gagal",
        }, status: 400
      end
    end

    def update
      @job_order = JobOrder.find(params[:id])

      if @job_order.update(job_order_params)
        render json:{
          values: {},
          message: "Sukses",
        }, status: 200
      else
        render json:{
          values: {},
          message: "Gagal",
        }, status: 400
      end
    end

    def destroy
      @job_order = JobOrder.find(params[:id])

      if @job_order.destroy
        render json:{
          values: {},
          message: "Sukses",
        }, status: 200
      else
        render json:{
          values: {},
          message: "Gagal",
        }, status: 400
      end
    end

    def job_order_params
      params.permit(:jobnumber, :staff, :time, :status, :customer, :point)
    end

    # Method untuk handling not found data untuk rescue handling diatas
    def notFound
      render json: {
          values: {},
          message: "Data Not Found!"
      }, status: 400
    end

    rescue_from ActiveRecord::RecordNotFound, with: :notFound
  end

app/controllers/job_orders_controller.rb
class JobOrdersController < ApplicationController
  before_action :set_job_order, only: [:show, :edit, :update, :destroy]

  # GET /job_orders
  # GET /job_orders.json
  def index
    @job_orders = JobOrder.all
    @job_order = JobOrder.new
  end

  # GET /job_orders/1
  # GET /job_orders/1.json
  def show
  end

  # GET /job_orders/new
  def new
    @job_order = JobOrder.new
  end

  # GET /job_orders/1/edit
  def edit
  end

  # POST /job_orders
  # POST /job_orders.json
  def create
    @job_order = JobOrder.new(job_order_params)

    respond_to do |format|
      if @job_order.save
        format.html { redirect_to @job_order, notice: 'Job order was successfully added.' }
        format.json { render :show, status: :created, location: @job_order }
      else
        format.html { render :new }
        format.json { render json: @job_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_orders/1
  # PATCH/PUT /job_orders/1.json
  def update
    respond_to do |format|
      if @job_order.update(job_order_params)
        format.html { redirect_to @job_order, notice: 'Job order was successfully updated.' }
        format.json { render :show, status: :ok, location: @job_order }
      else
        format.html { render :edit }
        format.json { render json: @job_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_orders/1
  # DELETE /job_orders/1.json
  def destroy
    @job_order.destroy
    respond_to do |format|
      format.html { redirect_to job_orders_url, notice: 'Job order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job_order
    @job_order = JobOrder.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def job_order_params
    params.require(:job_order).permit(:jobnumber, :staff_id, :customer_id, :time, :status, :point)
  end
end

app/helpers/api/v1/job_orders_helper.rb
module Api::V1::JobOrdersHelper
end

app/helpers/job_orders_helper.rb
module JobOrdersHelper
end

app/views/job_orders/_form.html.erb
<%= form_with(model: job_order, local: true) do |form| %>
  <% if @job_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_order.errors.count, "error") %> prohibited this job_order from being saved:</h2>

      <ul>
      <% @job_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" id="inJobnumber">
    <div class="input-field col s4">

      <% if @job_order.jobnumber.present? %>
        <%= form.label :jobnumber, "Job Number", class: 'active'%>
        <%= form.number_field :jobnumber, :readonly => true %>
      <% else %>
        <%= form.label :jobnumber, "Job Number", class: 'active' %>
        <%= form.number_field :jobnumber, :readonly => true, :value => rand(10 ** 10) %>
      <% end %>
    </div>
  </div>

  <div class="row" id="inStaff">
    <div class="input-field col s4">
      <div class="control-group">
        <%= form.label :staff, class: 'control-label' %>
        <div class="controls">
          <%= form.collection_select :staff_id, Staff.all, :id, :name, prompt: 'Select Staff'%>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="inCustomer">
    <div class="input-field col s4">
      <div class="control-group">
        <%= form.label :customer, class: 'control-label' %>
        <div class="controls">
          <%= form.collection_select :customer_id, Customer.all, :id, :name, prompt: 'Select Customer' %>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="intime">
    <div class="col s4">
      <%= form.label :time %>
      <%= form.text_field :time, id: 'datetimepicker'%>
    </div>
  </div>


  <div class="row" id="inStatus">
    <div class="input-field col s4">
      <div class="control-group">
        <%= form.label :status, class: 'control-label' %>
        <div class="controls">
          <%= form.select(:status, options_for_select([['Pending', 'pending'], ['On Progress', 'on_progress'],['Completed', 'completed']], disabled: ['on_progress', 'completed']))%>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="inStatus">
    <div class="input-field col s4">
      <div class="field">
        <%= form.label :point %>
        <%= form.text_field :point %>
      </div>
    </div>
  </div>


  <br>
  <div class="control-group">
    <div class="controls">
      <%= form.submit "Submit", class: "waves-effect waves-light btn" %>
    </div>
  </div>
<% end %>

app/views/job_orders/edit.html.erb
<h6>Editing Job Order</h6>

<%= render 'job_orders/form', job_order: @job_order %>

<!--<%#= link_to 'Show', @job_order %> |-->
<%= link_to 'Back', job_orders_path %>

app/views/job_orders/index.html.erb
<div><h5>Dashboard</h5></div>

<br>
<div class="row">
<div class="col s4">
    <div class="card horizontal">
      <div class="card-content">
        <div class="row">
          <i class="medium material-icons">assignment</i>
        </div>
        <div class="row center">
          <h6>JO List</h6>
        </div>
      </div>
      <div class="card-stacked">

        <div class="card-content">
          <div class="row center">
            <h5 class="orange-text text-lighten-2"><%= JobOrder.count %></h5>
          </div>
          <div class="row center span-text">
            Total
        </div>
        </div>
        <div class="card-action">
          Completed : <%= JobOrder.where(status: 'completed').count %>
        </div>
      </div>
    </div>
</div>
<div class="col s4">
    <div class="card horizontal">
      <%= link_to staffs_path do %>
      <div class="card-content">
        <div class="row">
          <i class="medium material-icons">person</i>
        </div>
        <div class="row center">
          <h6>Staff</h6>
        </div>
      </div>
      <% end %>
      <div class="card-stacked">
        <div class="card-content">
          <div class="row center">
            <h5 class="blue-text text-lighten-2"><%= Staff.count %></h5>
          </div>
          <div class="row center span-text">
            Total
          </div>
        </div>
        <div class="card-action">
          Working :  <%= JobOrder.where(status: 'on_progress').count %>
        </div>
      </div>

    </div>
</div>
<div class="col s4">
    <div class="card horizontal">
      <%= link_to customers_path do %>
      <div class="card-content">
        <div class="row center">
          <i class="medium material-icons">group</i>
        </div>

        <div class="row center">
          <h6>Customer</h6>
        </div>
      </div>
      <% end %>
      <div class="card-stacked">
        <div class="card-content">
          <div class="row center">
            <h5 class="blue-text text-darken-3"><%= Customer.count %></h5>
          </div>
          <div class="row center span-text">
            Total
          </div>
        </div>
        <div class="card-action">
            On Handling : <%= JobOrder.where(status: 'on_progress').count %>
        </div>
      </div>
    </div>
</div>
</div>
<p id="notice"><%= notice %></p>

<div class="row list-title">
  <i class="medium material-icons">assignment</i>
  <span>Recent Job Orders</span>
  <div class="right">
    <%= link_to '+ Add Job Order', '#ModalJO', class: "btn waves-effect waves-light modal-trigger"%>
  </div>
</div>

<div class="modal modal-add-jo" id="ModalJO">
  <h5 class="modal-close">&#10005;</h5>
  <div class="modal-content">
    <div class="title-add">
      Add Job Order
    </div>
    <%= render 'job_orders/form', job_order: @job_order %>
  </div>
</div>

<table class="responsive-table striped">
  <thead>
    <tr class="header-column">
      <th>Job Number</th>
      <th>Staff</th>
      <th>Time Appointment</th>
      <th>Status</th>
      <th>Customer Name</th>
      <th>Customer Point</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @job_orders.order('id Desc').each do |job_order| %>
      <tr>
        <td><%= job_order.jobnumber %></td>
        <td><%= job_order.staff.name %></td>
        <td><%= job_order.time %></td>
        <td><%= job_order.status.titleize %></td>
        <td><%= job_order.customer.name %></td>
        <td><%= job_order.customer.point %></td>
        <td><%= link_to '<i class="smallest material-icons">visibility</i>'.html_safe, job_order %></td>
        <td><%= link_to '<i class="smallest material-icons">create</i>'.html_safe, edit_job_order_path(job_order) %></td>
        <td><%= link_to '<i class="smallest material-icons">delete</i>'.html_safe, job_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/job_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Jobnumber:</strong>
  <%= @job_order.jobnumber %>
</p>

<p>
  <strong>Staff:</strong>
  <%= @job_order.staff.name %>
</p>

<p>
  <strong>Time Appointment:</strong>
  <%= @job_order.time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @job_order.status.titleize %>
</p>

<p>
  <strong>Customer Name:</strong>
  <%= @job_order.customer.name %>
</p>

<p>
  <strong>Customer Point:</strong>
  <%= @job_order.point %>
</p>

<%= link_to 'Edit', '#ModalJOEdit', class: "modal-trigger" %> |
<%= link_to 'Back', job_orders_path %>

<div class="modal modal-jo" id="ModalJOEdit">
  <h5 class="modal-close">&#10005;</h5>
  <div class="modal-content">
    <div class="title-add">
      Edit Job Order
    </div>
    <%= render 'job_orders/form', job_order: @job_order %>
  </div>
</div>